//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;
import java.io.PrintStream;
import visitor.SymbolTable;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class pass1<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //




   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String class_name = n.f1.f0.toString();
      class_data cdata = new class_data(class_name);
      SymbolTable.class_map.put(class_name, cdata);

      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      String method_name ="main";
      Method_data mdata = new Method_data(method_name,"void");
      cdata.m_methods.put(method_name, mdata);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String class_name = n.f1.f0.toString();
      class_data cdata = new class_data(class_name);
      SymbolTable.class_map.put(class_name, cdata);
      n.f2.accept(this, argu);
      if(n.f3.present())
      {
         for ( Enumeration<Node> e = n.f3.elements(); e.hasMoreElements(); ) {
            VarDeclaration var_decl = (VarDeclaration)e.nextElement();
            if(var_decl.f0.which == 0)
            {
               SimpleVarDeclaration simple_var_decl = (SimpleVarDeclaration)var_decl.f0.choice;
               String var_type = (String) simple_var_decl.f0.accept(this, argu);
               String var_name = simple_var_decl.f1.f0.toString();
               var_data vdata = new var_data(var_name, var_type);
               cdata.m_fields.put(var_name, vdata);
            }
            else
            {
               FinalVarDeclaration final_var_decl = (FinalVarDeclaration)var_decl.f0.choice;
               String var_type = (String) final_var_decl.f1.accept(this, argu);
               String var_name = final_var_decl.f2.f0.toString();
               var_data vdata = new var_data(var_name, var_type);
               vdata.is_final = true;
               cdata.m_fields.put(var_name, vdata);
            }
         }
      }
      // n.f3.accept(this, argu);

      n.f4.accept(this, (A)class_name);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String class_name = n.f1.f0.toString();
      class_data cdata = new class_data(class_name);
      SymbolTable.class_map.put(class_name, cdata);
      // n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      // n.f3.accept(this, argu);
      String parent_name = n.f3.f0.toString();
      cdata.parent_name = parent_name;
      if(n.f5.present())
      {
         for ( Enumeration<Node> e = n.f5.elements(); e.hasMoreElements(); ) {
            VarDeclaration var_decl = (VarDeclaration)e.nextElement();
            if(var_decl.f0.which == 0)
            {
               SimpleVarDeclaration simple_var_decl = (SimpleVarDeclaration)var_decl.f0.choice;
               String var_type = (String) simple_var_decl.f0.accept(this, argu);
               String var_name = simple_var_decl.f1.f0.toString();
               var_data vdata = new var_data(var_name, var_type);
               cdata.m_fields.put(var_name, vdata);
            }
            else
            {
               FinalVarDeclaration final_var_decl = (FinalVarDeclaration)var_decl.f0.choice;
               String var_type = (String) final_var_decl.f1.accept(this, argu);
               String var_name = final_var_decl.f2.f0.toString();
               var_data vdata = new var_data(var_name, var_type);
               vdata.is_final = true;
               cdata.m_fields.put(var_name, vdata);
            }
         }

      }

      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, (A)class_name);
      n.f7.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> SimpleVarDeclaration()
    *       | FinalVarDeclaration()
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(SimpleVarDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "final"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> Expression()
    * f5 -> ";"
    */
   public R visit(FinalVarDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;
      String class_name = (String)argu;
      class_data cdata = SymbolTable.class_map.get(class_name);
      String method_name = n.f2.f0.toString();
      String return_type = (String) n.f1.accept(this, argu);
      Method_data mdata = new Method_data(method_name, return_type);
      cdata.m_methods.put(method_name, mdata);

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      List<var_data>list= new ArrayList<>();
      n.f4.accept(this, (A)list);
      for(var_data vdata : list)
      {
         mdata.m_args.put(vdata.name, vdata);
      }
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      if(n.f7.present())
      {
         for ( Enumeration<Node> e = n.f7.elements(); e.hasMoreElements(); ) {
            VarDeclaration var_decl = (VarDeclaration)e.nextElement();
            if(var_decl.f0.which == 0)
            {
               SimpleVarDeclaration simple_var_decl = (SimpleVarDeclaration)var_decl.f0.choice;
               String var_type = (String) simple_var_decl.f0.accept(this, argu);
               String var_name = simple_var_decl.f1.f0.toString();
               var_data vdata = new var_data(var_name, var_type);
               mdata.m_vars.put(var_name, vdata);
            }
            else
            {
               FinalVarDeclaration final_var_decl = (FinalVarDeclaration)var_decl.f0.choice;
               String var_type = (String) final_var_decl.f1.accept(this, argu);
               String var_name = final_var_decl.f2.f0.toString();
               var_data vdata = new var_data(var_name, var_type);
               vdata.is_final = true;
               mdata.m_vars.put(var_name, vdata);
            }
         }
      }
      // n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;
      String type =  (String) n.f0.accept(this, argu);
      String name = n.f1.f0.toString();
      var_data vdata = new var_data(name, type);
      List<var_data> list = (List<var_data>) argu;
      list.add(vdata);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public R visit(Type n, A argu) {
      
      return n.f0.accept(this, argu);
      
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      String _ret="array";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      String _ret="boolean";
      n.f0.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      String _ret="int";
      n.f0.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | FieldAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | ForStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> Expression()
    * f5 -> ";"
    */
   public R visit(FieldAssignmentStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "for"
    * f1 -> "("
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> Expression()
    * f5 -> ";"
    * f6 -> Expression()
    * f7 -> ";"
    * f8 -> Identifier()
    * f9 -> "="
    * f10 -> Expression()
    * f11 -> ")"
    * f12 -> Statement()
    */
   public R visit(ForStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> AndExpression()
    *       | CompareExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<"
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(PlusExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      String _ret=n.f0.toString();
      n.f0.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> ( MessageSend() | PrimaryExpression() )
    */
   public R visit(NotExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   // public static void printSymbolTable() {
   //    printSymbolTable(System.out);
   // }

   // public static void printSymbolTable(PrintStream out) {
   //    if (out == null) {
   //       out = System.out;
   //    }

   //    Map<String, class_data> classes = new TreeMap<>(SymbolTable.class_map);
   //    out.println("===== Symbol Table =====");
   //    if (classes.isEmpty()) {
   //       out.println("(empty)");
   //       return;
   //    }

   //    for (Map.Entry<String, class_data> classEntry : classes.entrySet()) {
   //       String className = classEntry.getKey();
   //       class_data cdata = classEntry.getValue();

   //       String parent = (cdata == null) ? null : cdata.parent_name;
   //       if (parent != null) {
   //          out.println("Class: " + className + " extends " + parent);
   //       } else {
   //          out.println("Class: " + className);
   //       }

   //       Map<String, var_data> fields = new TreeMap<>();
   //       if (cdata != null && cdata.m_fields != null) {
   //          fields.putAll(cdata.m_fields);
   //       }
   //       out.println("  Fields:");
   //       if (fields.isEmpty()) {
   //          out.println("    (none)");
   //       } else {
   //          for (Map.Entry<String, var_data> fieldEntry : fields.entrySet()) {
   //             var_data v = fieldEntry.getValue();
   //             if (v == null) {
   //                out.println("    " + fieldEntry.getKey());
   //                continue;
   //             }
   //             String flags = "";
   //             if (v.is_final) flags += " final";
   //             if (v.is_initialized) flags += " initialized";
   //             if (!flags.isEmpty()) flags = " [" + flags.trim() + "]";
   //             out.println("    " + v.data_type + " " + v.name + flags);
   //          }
   //       }

   //       Map<String, Method_data> methods = new TreeMap<>();
   //       if (cdata != null && cdata.m_methods != null) {
   //          methods.putAll(cdata.m_methods);
   //       }
   //       out.println("  Methods:");
   //       if (methods.isEmpty()) {
   //          out.println("    (none)");
   //       } else {
   //          for (Map.Entry<String, Method_data> methodEntry : methods.entrySet()) {
   //             Method_data m = methodEntry.getValue();
   //             if (m == null) {
   //                out.println("    " + methodEntry.getKey());
   //                continue;
   //             }

   //             StringBuilder sig = new StringBuilder();
   //             sig.append(m.return_type).append(" ").append(m.name).append("(");
   //             if (m.arg_order != null && !m.arg_order.isEmpty()) {
   //                for (int i = 0; i < m.arg_order.size(); i++) {
   //                   String argName = m.arg_order.get(i);
   //                   String argType = (m.m_args == null) ? null : m.m_args.get(argName);
   //                   if (i > 0) sig.append(", ");
   //                   sig.append(argType == null ? "?" : argType).append(" ").append(argName);
   //                }
   //             }
   //             sig.append(")");
   //             out.println("    " + sig);

   //             Map<String, String> locals = new TreeMap<>();
   //             if (m.m_vars != null) locals.putAll(m.m_vars);
   //             out.println("      Locals:");
   //             if (locals.isEmpty()) {
   //                out.println("        (none)");
   //             } else {
   //                for (Map.Entry<String, String> localEntry : locals.entrySet()) {
   //                   out.println("        " + localEntry.getValue() + " " + localEntry.getKey());
   //                }
   //             }
   //          }
   //       }
   //    }
   // }

}
