//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class pass3<R,A> implements GJVisitor<R,A> {
   // Global CFG storage for each method signature
   public static Map<String, CFG> methodCFGs = new HashMap<>();
   
   // Phase 3: Liveness Analysis
   public static Map<String, Map<CFGNode, Set<String>>> livenessAnalysis = new HashMap<>();
   
   // Track current context during CFG building
   private String currClass = "";
   private String currMethod = "";
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> ( VarDeclaration() )*
    * f15 -> ( Statement() )*
    * f16 -> "}"
    * f17 -> "}"
    */
   public R visit(MainClass n, A argu) {
      R _ret=null;
      currClass = n.f1.f0.tokenImage;
      currMethod = "main";
      
      // Create CFG for main method
      String methodSig = currClass + ".main";
      CFG cfg = new CFG(methodSig);
      
      // Build CFG from main method body (no return for main)
      CFGBuilder builder = new CFGBuilder(cfg);
      builder.buildCFG(n.f15, null);  // No return statement for main
      
      // Store statement-to-CFGNode mapping
      cfg.setStatementToCFGNodeMap(builder.getStatementToCFGNodeMap());
      
      // Store CFG in global map
      methodCFGs.put(methodSig, cfg);
      
      // Print CFG for debugging
      cfg.printCFG();
      
      // Continue normal traversal
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      n.f17.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      currClass = n.f1.f0.tokenImage;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;
      currClass = n.f1.f0.tokenImage;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> ConstOrId()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;
      currMethod = n.f2.f0.tokenImage;
      
      // Create CFG for this method
      String methodSig = currClass + "." + currMethod;
      CFG cfg = new CFG(methodSig);
      
      // Extract parameter names from FormalParameterList (f4)
      if (n.f4.present()) {
          FormalParameterList paramList = (FormalParameterList) n.f4.node;
          
          // First parameter: f0 -> ConstOrId()
          // The parameter is Identifier, which is wrapped in the Type
          // FormalParameter: f0->Type f1->Identifier
          cfg.addParameterName(paramList.f0.f1.f0.tokenImage);  // First parameter name
          
          // Remaining parameters: f1 -> (FormalParameterRest)*
          // FormalParameterRest: f0->"," f1->FormalParameter
          if (paramList.f1.present()) {
              Enumeration<Node> rests = paramList.f1.elements();
              while (rests.hasMoreElements()) {
                  FormalParameterRest rest = (FormalParameterRest) rests.nextElement();
                  cfg.addParameterName(rest.f1.f1.f0.tokenImage);  // Parameter name
              }
          }
      }
      
      // Build CFG from method body (including return statement)
      CFGBuilder builder = new CFGBuilder(cfg);
      builder.buildCFG(n.f8, n.f10);  // Pass return ConstOrId
      
      // Store statement-to-CFGNode mapping
      cfg.setStatementToCFGNodeMap(builder.getStatementToCFGNodeMap());
      
      // Store CFG in global map
      methodCFGs.put(methodSig, cfg);
      
      // Print CFG for debugging
      cfg.printCFG();
      
      // Continue normal traversal
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public R visit(Type n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | FieldAssignmentStatement()
    *       | VoidMessageSendStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | ForStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> MessageSend()
    * f1 -> ";"
    */
   public R visit(VoidMessageSendStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> ConstOrId()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> ConstOrId()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> ConstOrId()
    * f5 -> ";"
    */
   public R visit(FieldAssignmentStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Identifier()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Identifier()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "for"
    * f1 -> "("
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> Expression()
    * f5 -> ";"
    * f6 -> Expression()
    * f7 -> ";"
    * f8 -> Identifier()
    * f9 -> "="
    * f10 -> Expression()
    * f11 -> ")"
    * f12 -> Statement()
    */
   public R visit(ForStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> ConstOrId()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> CompareExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | FieldRead()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ConstOrId()
    * f1 -> "<"
    * f2 -> ConstOrId()
    */
   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ConstOrId()
    * f1 -> "+"
    * f2 -> ConstOrId()
    */
   public R visit(PlusExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ConstOrId()
    * f1 -> "-"
    * f2 -> ConstOrId()
    */
   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ConstOrId()
    * f1 -> "*"
    * f2 -> ConstOrId()
    */
   public R visit(TimesExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> ConstOrId()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "."
    * f2 -> Identifier()
    */
   public R visit(FieldRead n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ArgList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ConstOrId()
    * f1 -> ( ArgRest() )*
    */
   public R visit(ArgList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> ConstOrId()
    */
   public R visit(ArgRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteralWithPosSign()
    *       | IntegerLiteralWithNegSign()
    *       | PlainIntegerLiteral()
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(PlainIntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "+"
    * f1 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteralWithPosSign n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "-"
    * f1 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteralWithNegSign n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | Identifier()
    *       | TrueLiteral()
    *       | FalseLiteral()
    */
   public R visit(ConstOrId n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> ConstOrId()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Identifier()
    */
   public R visit(NotExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }


   /**
    * Phase 2: Compute side effects for all methods after CFG construction
    * Side effects include: PrintStatement, FieldAssignmentStatement, AllocationExpression
    */
   /**
    * IMPROVED: Fixed-point iteration for transitive side-effect propagation.
    *
    * The original single-pass scan cannot propagate transitivity.
    * Example: if A calls B calls C, and C has a print statement, A and B
    * were incorrectly marked pure on the first pass.
    *
    * Algorithm:
    *  1. Seed all methods as pure.
    *  2. Scan every method's CFG for direct side effects (print, field write,
    *     array write).  Also check whether any callee is already marked impure.
    *  3. Repeat until stable (monotonically flips pure -> impure).
    *
    * Only reachable methods are scanned; dead methods are skipped so they
    * cannot falsely taint their callers.
    */
   public static void computeMethodSideEffects() {
      SymbolTable.methodSideEffects.clear();
      
      // Seed: all methods start as pure
      for (String methodSig : methodCFGs.keySet()) {
         SymbolTable.methodSideEffects.put(methodSig, false);
      }
      
      // Fixpoint: keep scanning until no new method flips from pure to impure
      boolean changed = true;
      while (changed) {
         changed = false;
         for (String methodSig : methodCFGs.keySet()) {
            // Skip unreachable methods - their side effects cannot be observed
            if (SymbolTable.unreachableMethods.contains(methodSig)) {
               continue;
            }
            // Already marked impure - nothing more to learn
            if (Boolean.TRUE.equals(SymbolTable.methodSideEffects.get(methodSig))) {
               continue;
            }
            
            CFG cfg = methodCFGs.get(methodSig);
            boolean hasSideEffect = false;
            for (CFGNode node : cfg.getNodes()) {
               if (containsSideEffect(node.getStatements(), methodSig)) {
                  hasSideEffect = true;
                  break;
               }
            }
            
            if (hasSideEffect) {
               SymbolTable.methodSideEffects.put(methodSig, true);
               changed = true;
            }
         }
      }
   }
   
   /**
    * IMPROVED containsSideEffect:
    *  - Added ArrayAssignmentStatement (arr[i] = v is a heap write)
    *  - Removed AllocationExpression as a side-effect source: a local
    *    allocation whose result is assigned to a dead local variable has no
    *    observable effect.  The constructor body itself is checked separately.
    *  - VoidMessageSend now consults the fixpoint summary map.
    */
   private static boolean containsSideEffect(List<Statement> statements, String methodSig) {
      if (statements == null || statements.isEmpty()) {
         return false;
      }
      
      for (Statement stmt : statements) {
         if (stmt == null || stmt.f0 == null) {
            continue;
         }
         
         Node actualStmt = stmt.f0.choice;
         if (actualStmt == null) {
            continue;
         }
         
         // PrintStatement is always a side effect
         if (actualStmt instanceof PrintStatement) {
            return true;
         }
         
         // FieldAssignmentStatement (obj.field = value) is a heap write
         if (actualStmt instanceof FieldAssignmentStatement) {
            return true;
         }
         
         // ADDED: ArrayAssignmentStatement (arr[i] = v) is a heap write
         if (actualStmt instanceof ArrayAssignmentStatement) {
            return true;
         }
         
         if (actualStmt instanceof AssignmentStatement) {
            AssignmentStatement assignStmt = (AssignmentStatement) actualStmt;
            
            // Writing to a class field is a side effect
            String varName = assignStmt.f0.f0.tokenImage;
            String className = extractClassFromMethodSignature(methodSig);
            if (isFieldOfClass(className, varName)) {
               return true;
            }
            
            // NOTE: AllocationExpression removed - local alloc with dead result
            // has no observable effect; the constructor is checked separately.
            
            // Check for MessageSend with side effects in the RHS expression
            if (containsMessageSendWithSideEffects(assignStmt.f2, methodSig)) {
               return true;
            }
         }
         
         // VoidMessageSendStatement: check fixpoint summary
         if (actualStmt instanceof VoidMessageSendStatement) {
            VoidMessageSendStatement msgStmt = (VoidMessageSendStatement) actualStmt;
            String calledMethodSig = extractMethodSignatureFromVoidMessage(msgStmt, methodSig);
            if (!calledMethodSig.equals("unknown") && hasSideEffects(calledMethodSig, methodSig)) {
               return true;
            }
         }
      }
      
      return false;
   }
   
   /**
    * Recursively check if an expression contains AllocationExpression
    */
   private static boolean containsAllocationInExpression(Expression expr) {
      if (expr == null || expr.f0 == null) {
         return false;
      }
      
      Node actualExpr = expr.f0.choice;
      if (actualExpr == null) {
         return false;
      }
      
      if (actualExpr instanceof AllocationExpression) {
         return true;
      }
      
      // Add more recursive checks as needed for complex expressions
      return false;
   }
   
   /**
    * Check if an expression contains a MessageSend to a method with side effects
    * Used for detecting recursive side effects in expressions
    */
   private static boolean containsMessageSendWithSideEffects(Expression expr, String methodSig) {
      if (expr == null || expr.f0 == null) {
         return false;
      }
      
      Object choice = expr.f0.choice;
      if (choice == null) {
         return false;
      }
      
      // Check if it's a MessageSend
      if (choice instanceof MessageSend) {
         MessageSend msgSend = (MessageSend) choice;
         String calledMethodSig = extractMethodSignatureFromMessageSend(msgSend, methodSig);
         if (!calledMethodSig.equals("unknown")) {
            return hasSideEffects(calledMethodSig, methodSig);
         }
      }
      
      return false;
   }
   
   /**
    * Extract method signature from a MessageSend node
    * Format: "ClassName.methodName" or "unknown"
    */
   private static String extractMethodSignatureFromMessageSend(MessageSend msgSend, String currentMethodSig) {
      try {
         // Get method name (f2 -> Identifier)
         String methodName = msgSend.f2.f0.tokenImage;
         
         // Get the object being called (f0 -> PrimaryExpression)
         PrimaryExpression primExpr = msgSend.f0;
         if (primExpr == null || primExpr.f0 == null) {
            return "unknown";
         }
         
         Object primChoice = primExpr.f0.choice;
         String className = null;
         
         // Case 1: this.method()
         if (primChoice instanceof ThisExpression) {
            className = extractClassFromMethodSignature(currentMethodSig);
         }
         // Case 2: obj.method() - obj is an identifier
         else if (primChoice instanceof Identifier) {
            Identifier objId = (Identifier) primChoice;
            String objName = objId.f0.tokenImage;
            className = tryToFindVariableType(objName, extractClassFromMethodSignature(currentMethodSig));
         }
         
         if (className != null && !className.isEmpty() && !className.equals("unknown")) {
            return className + "." + methodName;
         }
         
         return "unknown";
         
      } catch (Exception e) {
         return "unknown";
      }
   }
   
   /**
    * Extract the method signature from VoidMessageSendStatement
    * Handles: obj.method() or this.method()
    * Returns format: "ClassName.methodName" or "unknown" if cannot determine
    */
   private static String extractMethodSignatureFromVoidMessage(VoidMessageSendStatement stmt, String currentMethodSig) {
      try {
         MessageSend msgSend = stmt.f0;
         
         // Get method name (f2 -> Identifier)
         String methodName = msgSend.f2.f0.tokenImage;
         
         // Get the object being called (f0 -> PrimaryExpression)
         PrimaryExpression primExpr = msgSend.f0;
         if (primExpr == null || primExpr.f0 == null) {
            return "unknown";
         }
         
         Object primChoice = primExpr.f0.choice;
         String className = null;
         
         // Case 1: this.method()
         if (primChoice instanceof ThisExpression) {
            // Extract current class from methodSig (format: "ClassName.methodName")
            int dotIndex = currentMethodSig.lastIndexOf('.');
            if (dotIndex > 0) {
               className = currentMethodSig.substring(0, dotIndex);
            }
         }
         // Case 2: obj.method() - obj is an identifier
         else if (primChoice instanceof Identifier) {
            Identifier objId = (Identifier) primChoice;
            String objName = objId.f0.tokenImage;
            
            // Try to find the type of obj in the current class's symbol table
            int dotIndex = currentMethodSig.lastIndexOf('.');
            if (dotIndex > 0) {
               String currClass = currentMethodSig.substring(0, dotIndex);
               // Look for the variable in the class or method
               // For now, we'll try to infer from available information
               // If variable is found in class, get its type
               if (SymbolTable.class_map.containsKey(currClass)) {
                  // Try to find variable type - check fields and local variables
                  // This is a simplified approach
                  className = tryToFindVariableType(objName, currClass);
               }
            }
         }
         
         // Build signature if we have className
         if (className != null && !className.isEmpty() && !className.equals("unknown")) {
            String signature = className + "." + methodName;
            return signature;
         }
         
         return "unknown";
         
      } catch (Exception e) {
         return "unknown";
      }
   }
   
   /**
    * Helper method to find variable type from class data
    */
   private static String tryToFindVariableType(String varName, String className) {
      if (SymbolTable.class_map.containsKey(className)) {
         class_data classData = SymbolTable.class_map.get(className);
         // Check if it's a field
         if (classData.m_fields.containsKey(varName)) {
            return classData.m_fields.get(varName).data_type;
         }
      }
      return "unknown";
   }
   
   /**
    * Extract class name from method signature (format: "ClassName.methodName")
    */
   private static String extractClassFromMethodSignature(String methodSig) {
      int dotIndex = methodSig.lastIndexOf('.');
      if (dotIndex > 0) {
         return methodSig.substring(0, dotIndex);
      }
      return "";
   }
   
   /**
    * Check if a variable is a field of the given class
    */
   private static boolean isFieldOfClass(String className, String varName) {
      if (className == null || className.isEmpty() || varName == null) {
         return false;
      }
      
      if (SymbolTable.class_map.containsKey(className)) {
         class_data classData = SymbolTable.class_map.get(className);
         return classData.m_fields.containsKey(varName);
      }
      
      return false;
   }
   
   /**
    * Check if a method (by signature) has side effects (memoized lookup)
    */
   private static boolean hasSideEffects(String methodSig, String currentMethod) {
      // Avoid infinite recursion
      if (methodSig.equals(currentMethod) || methodSig.equals("unknown")) {
         return false;
      }
      
      if (SymbolTable.methodSideEffects.containsKey(methodSig)) {
         return SymbolTable.methodSideEffects.get(methodSig);
      }
      
      // Conservative approach: assume unknown methods have side effects
      return true;
   }
   
   /**
    * Phase 3: Compute liveness analysis for all methods after CFG construction
    * Determines which variables are live (used) at each point in the CFG
    * Uses backward pass from exit to entry with proper propagation
    * - LiveIn(node) = USE(node) ∪ (LiveOut(node) - DEF(node))
    * - LiveOut(node) = ∪ LiveIn(successor) for all successors
    */
   // Reset all static fields for next optimization iteration
   public static void reset() {
      methodCFGs.clear();
      livenessAnalysis.clear();
   }
   
   public static void computeLivenessAnalysis() {
      livenessAnalysis.clear();
      
      // System.out.println("\n=== PHASE 3: LIVENESS ANALYSIS (USE/DEF) ===");
      
      // Analyze each method's CFG
      for (String methodSig : methodCFGs.keySet()) {
         CFG cfg = methodCFGs.get(methodSig);
         Map<CFGNode, Set<String>> liveIn = new HashMap<>();
         Map<CFGNode, Set<String>> liveOut = new HashMap<>();
         Map<CFGNode, Set<String>> useSet = new HashMap<>();
         Map<CFGNode, Set<String>> defSet = new HashMap<>();
         
         // System.out.println("\n--- Method: " + methodSig + " ---");
         
         // Step 1: Initialize use/def sets for allnodes
         for (CFGNode node : cfg.getNodes()) {
            liveIn.put(node, new HashSet<>());
            liveOut.put(node, new HashSet<>());
            Set<String> use = new HashSet<>();
            Set<String> def = new HashSet<>();
            
            // Extract use and def from statements
            if (node.getStatements() != null && !node.getStatements().isEmpty()) {
               for (Statement stmt : node.getStatements()) {
                  extractUseDefFromStatement(stmt, use, def);
               }
            }
            
            // Special handling for return nodes
            String nodeLabel = node.getLabel();
            if (nodeLabel.contains("return")) {
               String returnVar = node.getReturnVariable();
               if (returnVar != null && !returnVar.isEmpty()) {
                  use.add(returnVar);
               }
            }
            
            useSet.put(node, use);
            defSet.put(node, def);
            
            if (!use.isEmpty() || !def.isEmpty()) {
               // System.out.println("  Node: " + node.getLabel());
               // System.out.println("    USE: " + use);
               // System.out.println("    DEF: " + def);
            }
         }
         
         // Step 2: Extract condition variables from if/while nodes
         for (CFGNode node : cfg.getNodes()) {
            String nodeLabel = node.getLabel();
            if (nodeLabel.contains("if_cond") || nodeLabel.contains("while_cond")) {
               // Find the predecessor statement that contains the condition variable
               for (CFGNode pred : cfg.getNodes()) {
                  if (pred.getSuccessors().contains(node)) {
                     // This is likely the node with the condition assignment
                     if (pred.getStatements() != null) {
                        for (Statement stmt : pred.getStatements()) {
                           if (stmt != null && stmt.f0 != null && stmt.f0.choice instanceof AssignmentStatement) {
                              AssignmentStatement assign = (AssignmentStatement) stmt.f0.choice;
                              String condVar = assign.f0.f0.tokenImage;
                              useSet.get(node).add(condVar);
                           }
                        }
                     }
                  }
               }
               if (!useSet.get(node).isEmpty()) {
                  // System.out.println("  Node: " + node.getLabel());
                  // System.out.println("    USE: " + useSet.get(node));
                  // System.out.println("    DEF: " + defSet.get(node));
               }
            }
         }
         
         // Step 3: Backward pass - iterate until fixpoint
         boolean changed = true;
         int iterations = 0;
         
         while (changed && iterations < 100) {
            changed = false;
            iterations++;
            
            // Traverse nodes in reverse order for backward analysis
            List<CFGNode> nodes = new ArrayList<>(cfg.getNodes());
            Collections.reverse(nodes);
            
            for (CFGNode node : nodes) {
               Set<String> oldLiveIn = new HashSet<>(liveIn.get(node));
               Set<String> oldLiveOut = new HashSet<>(liveOut.get(node));
               
               // Compute new liveOut = union of liveIn from all successors
               Set<String> newLiveOut = new HashSet<>();
               for (CFGNode succ : node.getSuccessors()) {
                  if (liveIn.containsKey(succ)) {
                     newLiveOut.addAll(liveIn.get(succ));
                  }
               }
               
               // Compute new liveIn = USE ∪ (liveOut - DEF)
               Set<String> newLiveIn = new HashSet<>(useSet.get(node));
               Set<String> liveOutMinusDef = new HashSet<>(newLiveOut);
               liveOutMinusDef.removeAll(defSet.get(node));
               newLiveIn.addAll(liveOutMinusDef);
               
               // Update if changed
               if (!newLiveIn.equals(oldLiveIn) || !newLiveOut.equals(oldLiveOut)) {
                  liveIn.put(node, newLiveIn);
                  liveOut.put(node, newLiveOut);
                  changed = true;
               }
            }
         }
         
         // Step 4: Store results
         livenessAnalysis.put(methodSig, liveOut);
         SymbolTable.liveness.put(methodSig, new HashMap<>(liveOut));
         
         // System.out.println("\n  --- Final Liveness Results (after " + iterations + " iterations) ---");
         for (CFGNode node : cfg.getNodes()) {
            Set<String> nodeIn = liveIn.get(node);
            Set<String> nodeOut = liveOut.get(node);
            Set<String> nodeUse = useSet.get(node);
            Set<String> nodeDef = defSet.get(node);
            
            // System.out.println("  Node " + node.getLabel() + ":");
            // System.out.println("    USE: " + nodeUse + ", DEF: " + nodeDef);
            // System.out.println("    LiveIn: " + nodeIn + ", LiveOut: " + nodeOut);
         }
      }
      
      // System.out.println();
   }
   
   /**
    * Extract USE and DEF sets from a statement
    * USE = variables read in the statement
    * DEF = variables written in the statement
    */
   private static void extractUseDefFromStatement(Statement stmt, Set<String> use, Set<String> def) {
      if (stmt == null || stmt.f0 == null) return;
      
      Object choice = stmt.f0.choice;
      
      if (choice instanceof AssignmentStatement) {
         AssignmentStatement assign = (AssignmentStatement) choice;
         // DEF: left side variable
         if (assign.f0 != null) {
            def.add(assign.f0.f0.tokenImage);
         }
         // USE: right side expression variables
         extractUseFromExpression(assign.f2, use);
         
      } else if (choice instanceof FieldAssignmentStatement) {
         FieldAssignmentStatement fieldAssign = (FieldAssignmentStatement) choice;
         // USE: object and right side
         use.add(fieldAssign.f0.f0.tokenImage);
         extractUseFromConstOrId(fieldAssign.f4, use);
         
      } else if (choice instanceof ArrayAssignmentStatement) {
         ArrayAssignmentStatement arrayAssign = (ArrayAssignmentStatement) choice;
         // USE: array, index, and right side
         use.add(arrayAssign.f0.f0.tokenImage);
         extractUseFromConstOrId(arrayAssign.f2, use);
         extractUseFromConstOrId(arrayAssign.f5, use);
         
      } else if (choice instanceof IfStatement) {
         IfStatement ifStmt = (IfStatement) choice;
         // USE: condition
         use.add(ifStmt.f2.f0.tokenImage);
         
      } else if (choice instanceof WhileStatement) {
         WhileStatement whileStmt = (WhileStatement) choice;
         // USE: condition
         use.add(whileStmt.f2.f0.tokenImage);

      } else if (choice instanceof ForStatement) {
         ForStatement forStmt = (ForStatement) choice;

         // DEF: initializer variable and update target variable
         if (forStmt.f2 != null) {
            def.add(forStmt.f2.f0.tokenImage);
         }
         if (forStmt.f8 != null) {
            def.add(forStmt.f8.f0.tokenImage);
         }

         // USE: variables used in init/condition/update expressions
         extractUseFromExpression(forStmt.f4, use);
         extractUseFromExpression(forStmt.f6, use);
         extractUseFromExpression(forStmt.f10, use);
         
      } else if (choice instanceof PrintStatement) {
         PrintStatement printStmt = (PrintStatement) choice;
         // USE: expression being printed
         extractUseFromConstOrId(printStmt.f2, use);
         
      } else if (choice instanceof VoidMessageSendStatement) {
         VoidMessageSendStatement voidMsg = (VoidMessageSendStatement) choice;
         // USE: object and arguments
         MessageSend msgSend = voidMsg.f0;
         extractUseFromPrimaryExpression(msgSend.f0, use);
         if (msgSend.f4.present()) {
            Node argNode = msgSend.f4.node;
            if (argNode instanceof ArgList) {
               ArgList argList = (ArgList) argNode;
               extractUseFromConstOrId(argList.f0, use);
               if (argList.f1.present()) {
                  Enumeration<Node> argRests = argList.f1.elements();
                  while (argRests.hasMoreElements()) {
                     ArgRest rest = (ArgRest) argRests.nextElement();
                     extractUseFromConstOrId(rest.f1, use);
                  }
               }
            }
         }
      }
   }
   
   /**
    * Extract variables from an Expression (recursive)
    */
   private static void extractUseFromExpression(Expression expr, Set<String> use) {
      if (expr == null || expr.f0 == null) return;
      
      Object choice = expr.f0.choice;
      
      if (choice instanceof PrimaryExpression) {
         extractUseFromPrimaryExpression((PrimaryExpression) choice, use);
      } else if (choice instanceof CompareExpression) {
         CompareExpression cmp = (CompareExpression) choice;
         extractUseFromConstOrId(cmp.f0, use);
         extractUseFromConstOrId(cmp.f2, use);
      } else if (choice instanceof PlusExpression) {
         PlusExpression plus = (PlusExpression) choice;
         extractUseFromConstOrId(plus.f0, use);
         extractUseFromConstOrId(plus.f2, use);
      } else if (choice instanceof MinusExpression) {
         MinusExpression minus = (MinusExpression) choice;
         extractUseFromConstOrId(minus.f0, use);
         extractUseFromConstOrId(minus.f2, use);
      } else if (choice instanceof TimesExpression) {
         TimesExpression times = (TimesExpression) choice;
         extractUseFromConstOrId(times.f0, use);
         extractUseFromConstOrId(times.f2, use);
      } else if (choice instanceof ArrayLookup) {
         ArrayLookup arrayLookup = (ArrayLookup) choice;
         use.add(arrayLookup.f0.f0.tokenImage);
         extractUseFromConstOrId(arrayLookup.f2, use);
      } else if (choice instanceof ArrayLength) {
         ArrayLength arrayLength = (ArrayLength) choice;
         use.add(arrayLength.f0.f0.tokenImage);
      } else if (choice instanceof MessageSend) {
         MessageSend msgSend = (MessageSend) choice;
         // Object being called on
         extractUseFromPrimaryExpression(msgSend.f0, use);
         // Arguments to the method
         if (msgSend.f4.present()) {
            Node argNode = msgSend.f4.node;
            if (argNode instanceof ArgList) {
               ArgList argList = (ArgList) argNode;
               extractUseFromConstOrId(argList.f0, use);
               if (argList.f1.present()) {
                  Enumeration<Node> argRests = argList.f1.elements();
                  while (argRests.hasMoreElements()) {
                     ArgRest rest = (ArgRest) argRests.nextElement();
                     extractUseFromConstOrId(rest.f1, use);
                  }
               }
            }
         }
      } else if (choice instanceof FieldRead) {
         FieldRead fieldRead = (FieldRead) choice;
         use.add(fieldRead.f0.f0.tokenImage);
      }
   }
   
   /**
    * Extract variables from ConstOrId
    */
   private static void extractUseFromConstOrId(ConstOrId c, Set<String> use) {
      if (c == null || c.f0 == null) return;
      
      Object choice = c.f0.choice;
      if (choice instanceof Identifier) {
         Identifier id = (Identifier) choice;
         use.add(id.f0.tokenImage);
      }
   }
   
   /**
    * Extract variables from PrimaryExpression
    */
   private static void extractUseFromPrimaryExpression(PrimaryExpression prim, Set<String> use) {
      if (prim == null || prim.f0 == null) return;
      
      Object choice = prim.f0.choice;
      if (choice instanceof Identifier) {
         Identifier id = (Identifier) choice;
         use.add(id.f0.tokenImage);
      }
   }

}