//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;


public class pass1<R,A> implements GJVisitor<R,A> {
   



   String concat = "\n";
   int temp_count=10;
   String new_temp()
   {
      String temp = "temp"+temp_count;
      temp_count++;
      return temp;
   }
   Map<String, String> temp_to_type = new HashMap<String, String>();
   String currclass = "";
   String currmethod = "";
   String  id_to_type(String var_name)
   {
      if(SymbolTable.class_map.get(currclass).m_methods.get(currmethod).m_vars.containsKey(var_name))
      {
         return SymbolTable.class_map.get(currclass).m_methods.get(currmethod).m_vars.get(var_name).data_type;
      }
      if(SymbolTable.class_map.get(currclass).m_methods.get(currmethod).m_args.containsKey(var_name))
      {
         return SymbolTable.class_map.get(currclass).m_methods.get(currmethod).m_args.get(var_name).data_type;
      }
      else if(SymbolTable.class_map.get(currclass).m_fields.containsKey(var_name))
      {
         return SymbolTable.class_map.get(currclass).m_fields.get(var_name).data_type;
      }
      else
      {
         String class_name = SymbolTable.class_map.get(currclass).parent_name;
         while(class_name!=null)
         {
            if(SymbolTable.class_map.get(class_name).m_fields.containsKey(var_name))
            {
               return SymbolTable.class_map.get(class_name).m_fields.get(var_name).data_type;
            }
            class_name = SymbolTable.class_map.get(class_name).parent_name;
         }
         return null;
      }
   }
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }


   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {

      currclass = n.f1.f0.toString();
      currmethod = "main";
      String print = "";
      R _ret=null;
      print +=" class " + n.f1.f0.toString() + " {\n";
      print +=" public static void main (String [] " + n.f11.f0.toString() + "){\n";
      n.f14.accept(this, argu);
      for(int i=10;i<temp_count;i++){
         print +=temp_to_type.get("temp"+i)+" temp"+i+";\n";
      }
      print +=concat+" }\n"+" }\n";
      System.out.println(print);
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( SimpleVarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      currclass = n.f1.f0.toString();
      String print = " ";
      R _ret=null;
      print +=" class " + n.f1.f0.toString() + " {\n";
      for(Enumeration<Node> e = n.f3.elements(); e.hasMoreElements(); ) {
         SimpleVarDeclaration temp = (SimpleVarDeclaration) e.nextElement();
         String type = (String) temp.f0.accept(this, argu);
         String name = temp.f1.f0.toString();
         print += " "+type+" "+name+";\n";
      }
      System.out.println(print);
      n.f4.accept(this, argu);
      System.out.println(" }\n");
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( SimpleVarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      
      String print = " ";
      R _ret=null;
      currclass = n.f1.f0.toString();
      print +=" class " + n.f1.f0.toString() + " extends "
      + n.f3.f0.toString() + " {\n";
      for(Enumeration<Node> e = n.f5.elements(); e.hasMoreElements(); )
      {
         SimpleVarDeclaration temp = (SimpleVarDeclaration) e.nextElement();
         String type = (String) temp.f0.accept(this, argu);
         String name = temp.f1.f0.toString();
         print += " "+type+" "+name+";\n";
      }
      System.out.println(print);
      n.f6.accept(this, argu);
      System.out.println(" }\n");
      return _ret;
   }

   /**
    * f0 -> SimpleVarDeclaration()
    *       | FinalVarDeclaration()
    */
   public R visit(VarDeclaration n, A argu) {
     return n.f0.accept(this, argu);
      
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(SimpleVarDeclaration n, A argu) {
      String _ret = "";
      _ret += n.f0.accept(this, argu) + " " + n.f1.f0.toString() + ";\n";
      return (R) _ret;
   }

   /**
    * f0 -> "final"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> Expression()
    * f5 -> ";"
    */
   public R visit(FinalVarDeclaration n, A argu) {
      String _ret = "";
      _ret +=n.f1.accept(this, argu) + " " + n.f2.f0.toString()+" ;\n";
      return (R) _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {

      String print = " ";
      R _ret=null;
      currmethod = n.f2.f0.toString();
      temp_to_type.clear();
      temp_count=10;
      concat = "\n";
      String type = (String)n.f1.accept(this, argu);
      print +=" public " + type + " " +
      n.f2.f0.toString() + " (";
      if(n.f4.present()) print +=(String)n.f4.accept(this, argu);
      print +="){\n";
      for(Enumeration<Node> e = n.f7.elements(); e.hasMoreElements(); ) {
         VarDeclaration temp = (VarDeclaration) e.nextElement();
         print +=temp.accept(this, argu);
         print +="\n";
      }
      String print2="";
      for(Enumeration<Node> e = n.f7.elements();e.hasMoreElements();){
         VarDeclaration temp = (VarDeclaration) e.nextElement();
         if(temp.f0.which==1){
            
            FinalVarDeclaration var = (FinalVarDeclaration) temp.f0.choice;
            print2 +="\n"+var.f2.f0.toString() + " = " + var.f4.accept(this, argu) + ";\n";

         }
      }
      print2=concat+ " " + print2;
      concat = "";
      n.f8.accept(this, argu);
      String p  = " return " + n.f10.accept(this, argu) + ";\n";
      print2=print2+concat +p+" }\n";
      for(int i=10;i<temp_count;i++){
         print +=temp_to_type.get("temp"+i)+" temp"+i+";\n";
      }
      print =print + print2;
      System.out.println(print);
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      String _ret="";
      _ret += (String) n.f0.accept(this, argu);
      for (Enumeration<Node> e = n.f1.elements(); e.hasMoreElements(); ) {
         _ret += (String) e.nextElement().accept(this, argu);
      }
      return (R) _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      String  _ret="";
      _ret += (String)n.f0.accept(this, argu) + " " + n.f1.f0.toString();
      return (R) _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      String _ret=" , ";
      _ret += (String) n.f1.accept(this, argu);
      return (R) _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public R visit(Type n, A argu) {
      String _ret;
      if(n.f0.which==0){
         _ret = "int[]";
      }
      else if(n.f0.which==1){
         _ret = "boolean";
      }
      else if(n.f0.which==2){
         _ret = "int";
      }
      else{
         _ret = ((Identifier)n.f0.choice).f0.toString();
      }
      return (R) _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | FieldAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | ForStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      concat+="{\n";
      n.f1.accept(this, argu);
      concat+="}\n";
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      String print = n.f0.f0.toString() + " = " + n.f2.accept(this, argu) + ";\n";
      concat += print;
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      String print = n.f0.f0.toString() + " [ " + n.f2.accept(this, argu) + " ] = " + n.f5.accept(this, argu) + ";\n";
      concat += print;
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> Expression()
    * f5 -> ";"
    */
   public R visit(FieldAssignmentStatement n, A argu) {
      R _ret=null;
      String print = n.f0.accept(this, argu) + " . " + n.f2.f0.toString() + " = " + n.f4.accept(this, argu) + ";\n";
      concat += print;
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      String print = "if ( " + n.f2.accept(this, argu) + " ) {\n";
      concat += print;
      n.f4.accept(this, argu);
      concat += "}\n else {\n";
      n.f6.accept(this, argu);
      concat += "}\n";
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      String saved = concat;
      concat = "";
      String cond_temp = (String) n.f2.accept(this, argu);
      String cond_preamble = concat;
      concat = saved + cond_preamble + "while ( " + cond_temp + " ) {\n";
      n.f4.accept(this, argu);
      concat += cond_preamble;
      concat += "}\n";
      return _ret;
   }


   /**
    * f0 -> "for"
    * f1 -> "("
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> Expression()
    * f5 -> ";"
    * f6 -> Expression()
    * f7 -> ";"
    * f8 -> Identifier()
    * f9 -> "="
    * f10 -> Expression()
    * f11 -> ")"
    * f12 -> Statement()
    */
   public R visit(ForStatement n, A argu) {
    
      R _ret=null;
      String saved = concat;
      concat = "";

      String init_temp = (String) n.f4.accept(this, argu);
      String init_string = concat;
      concat = "";

      String cond_temp = (String) n.f6.accept(this, argu);
      String cond_string = concat;
      concat = "";

      String temp_iterator = (String) n.f10.accept(this, argu);
      String iterator_string = concat;

      concat = saved;
      concat += init_string;
      concat += n.f2.f0.toString() + " = " + init_temp + ";\n";
      concat += cond_string;
      concat += "while ( " + cond_temp + " ) {\n";
      n.f12.accept(this, argu);
      concat += iterator_string;
      concat += n.f8.f0.toString() + " = " + temp_iterator + ";\n";
      concat += cond_string;
      concat += "}\n";
      return _ret;

   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      String print = "System.out.println ( " + n.f2.accept(this, argu) + " ) ;\n";
      concat += print;
      return _ret;
   }

   /**
    * f0 -> ORExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
    
      return n.f0.accept(this, argu);

   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      
      String print = " ";
      String temp1=new_temp();
      temp_to_type.put(temp1, "boolean");
      String temp2=new_temp();temp_to_type.put(temp2, "boolean");
      String temp3=new_temp();temp_to_type.put(temp3, "boolean");
      print += temp1 + " = " + n.f0.accept(this, argu) + ";\n";
      print += temp2 + " = " + n.f2.accept(this, argu) + ";\n";
      print += "if("+temp1+" )"+"{\n"+temp3+" = "+temp2+";\n}\n else {\n"+temp3+" = false;\n}\n";
      concat += print;
      return (R)temp3;

   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "|"
    * f2 -> PrimaryExpression()
    */
   public R visit(ORExpression n, A argu) {
      R _ret=null;
      String print = " ";
      String temp1=new_temp();temp_to_type.put(temp1, "boolean");
      String temp2=new_temp();temp_to_type.put(temp2, "boolean");
      String temp3=new_temp();temp_to_type.put(temp3, "boolean");
      print += temp1 + " = " + n.f0.accept(this, argu) + ";\n";
      print += temp2 + " = " + n.f2.accept(this, argu) + ";\n";
      print += "if("+temp1+" )"+"{\n"+temp3+" = true;\n}\n else {\n"+temp3+" = "+temp2+";\n}\n";
      concat += print;
      return (R)temp3;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<"
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      String print = " ";
      String temp1=new_temp();temp_to_type.put(temp1, "int");
      String temp2=new_temp();temp_to_type.put(temp2, "int");
      String temp3=new_temp();temp_to_type.put(temp3, "boolean");
      print += temp1 + " = " + n.f0.accept(this, argu) + ";\n";
      print += temp2 + " = " + n.f2.accept(this, argu) + ";\n";
      print += temp3 + " = " + temp1 + " < " + temp2 + ";\n";
      concat += print;
      return (R)temp3;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(PlusExpression n, A argu) {
      R _ret=null;
      String print = " ";
      String temp1=new_temp();temp_to_type.put(temp1, "int");
      String temp2=new_temp();temp_to_type.put(temp2, "int");
      String temp3=new_temp();temp_to_type.put(temp3, "int");
      print += temp1 + " = " + n.f0.accept(this, argu) + ";\n";
      print += temp2 + " = " + n.f2.accept(this, argu) + ";\n";
      print += temp3 + " = " + temp1 + " + " + temp2 + ";\n";
      concat += print;
      return (R)temp3;

   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      String print = " ";
      String temp1=new_temp();temp_to_type.put(temp1, "int");
      String temp2=new_temp();temp_to_type.put(temp2, "int");
      String temp3=new_temp();temp_to_type.put(temp3, "int");
      print += temp1 + " = " + n.f0.accept(this, argu) + ";\n";
      print += temp2 + " = " + n.f2.accept(this, argu) + ";\n";
      print += temp3 + " = " + temp1 + " - " + temp2 + ";\n";
      concat += print;
      return (R)temp3;
      
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
      R _ret=null;
      String print = " ";
      String temp1=new_temp();temp_to_type.put(temp1, "int");
      String temp2=new_temp();temp_to_type.put(temp2, "int");
      String temp3=new_temp();temp_to_type.put(temp3, "int");
      print += temp1 + " = " + n.f0.accept(this, argu) + ";\n";
      print += temp2 + " = " + n.f2.accept(this, argu) + ";\n";
      print += temp3 + " = " + temp1 + " * " + temp2 + ";\n";
      concat += print;
      return (R)temp3;

   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      String print = " ";
      String temp1=new_temp();temp_to_type.put(temp1, "int[]");
      String temp2=new_temp();temp_to_type.put(temp2, "int");
      String temp3=new_temp();temp_to_type.put(temp3, "int");
      print += temp1 + " = " + n.f0.accept(this, argu) + ";\n";
      print += temp2 + " = " + n.f2.accept(this, argu) + ";\n";
      print += temp3 + " = " + temp1 + " [ " + temp2 + " ] ;\n";
      concat += print;
      return (R)temp3;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      String print = " ";
      String temp1=new_temp();temp_to_type.put(temp1, "int[]");
      String temp2=new_temp();temp_to_type.put(temp2, "int");
      print += temp1 + " = " + n.f0.accept(this, argu) + ";\n";
      print += temp2 + " = " + temp1 + ".length;\n";
      concat += print;
      return (R)temp2;

   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {

      String temp1=(String) n.f0.accept(this, argu);
      String method_name = n.f2.f0.toString();
      String type = temp_to_type.get(temp1);
      Method_data method = SymbolTable.class_map.get(type).m_methods.get(method_name);
      String print = " ";
      String temp2=new_temp();temp_to_type.put(temp2, method.return_type);
      print += temp2 + " = " + temp1 + " . " + method_name + " ( ";
      if(n.f4.present()){
         String args = (String)n.f4.accept(this, argu);
         print += args;
      }
      print += " ) ;\n";
      concat += print;
      return (R)temp2;

      
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      
      String _ret="";
      _ret += n.f0.accept(this, argu);
      for (Enumeration<Node> e = n.f1.elements(); e.hasMoreElements(); ) {
         _ret += e.nextElement().accept(this, argu);
      }
      return (R) _ret;

   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      String _ret=" , ";
      _ret += n.f1.accept(this, argu);
      return (R) _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      
      String print = "";
      String temp1=new_temp();temp_to_type.put(temp1, "int");
      print+= temp1 + " = " + n.f0.toString() + ";\n";
      concat += print;
      return (R)temp1;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {

      String print = "";
      String temp1=new_temp();temp_to_type.put(temp1, "boolean");
      print += temp1 + " = true;\n";
      concat += print;
      return (R)temp1;

   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      String print = "";
      String temp1=new_temp();temp_to_type.put(temp1, "boolean");
      print += temp1 + " = false;\n";
      concat += print;
      return (R)temp1;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      
      String print = "";
      String temp1=new_temp();temp_to_type.put(temp1,id_to_type(n.f0.toString()) );
      print += temp1 + " = " + n.f0.toString() + ";\n";
      concat += print;
      return (R)temp1;

   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      String print ="";
      String temp1 = new_temp();temp_to_type.put(temp1, currclass);
      print += temp1 + " = this;\n";
      concat += print;
      return (R)temp1;

   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      String temp1=new_temp();temp_to_type.put(temp1, "int");
      String temp2=new_temp();temp_to_type.put(temp2, "int[]");
      String print = " ";
      print += temp1 + " = " + n.f3.accept(this, argu)+ ";\n";
      print += temp2 + " = new int [ " + temp1 + " ] ;\n";
      concat += print;
      return (R)temp2;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      String temp1=new_temp();temp_to_type.put(temp1, n.f1.f0.toString());
      String print = " ";
      print += temp1 + " = new " + n.f1.f0.toString() + " ( ) ;\n";
      concat += print;
      return (R)temp1;
   }

   /**
    * f0 -> "!"
    * f1 -> ( MessageSend() | PrimaryExpression() )
    */
   public R visit(NotExpression n, A argu) {
      String temp1=new_temp();temp_to_type.put(temp1, "boolean");
      String temp2=new_temp();temp_to_type.put(temp2, "boolean");
      String print = " ";
      print += temp1 + " = " + n.f1.accept(this, argu) + ";\n";
      print += temp2 + " = !" + temp1 + ";\n";
      concat += print;
      return (R)temp2;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      
         return n.f1.accept(this, argu);

   }

}
